### ISSUE TITLE
Silent Arming Not Silencing the Beeps on Arm Stay

### ISSUE THREAD

**Issue by rbiffle** [schwark/smartthings-alarmcom#1]
I've installed your amazing app and device in STs.  All works wonderfully.  I have a small issue where the arming stay will not be silent.  I've turned off silent arming (via the thing settings), saved the change, then turned it back on and saved the change.  Either way, my system still beeps during arming.  Any suggestions to fix this issue?  Thanks in advance for you assistance.

**Comment by schwark** [comment]
I would love to help, but I am unable to replicate the issue. So I am adding a bunch of logging. Please update device type and smartapp with this new app and send me log lines (from live loggin in your IDE) that contain: "got command"

**Comment by rbiffle** [comment]
Thank you @schwark !  I followed the upgrade instructions in the readme file.  I will give it some time to arm and disarm then send you the files.

**Comment by schwark** [comment]
I am unable to replicate and looks like the fix requires an entire rebuild with the full site, which I don't have the time to do unfortunately.
