### ISSUE TITLE
alarm.com backside functionality stoped working this morning

### ISSUE THREAD

**Issue by MattAH64** [schwark/smartthings-alarmcom#11]
your app does what it is supposed to on the front side. After a arm/disarm button/routine is ran, I get the notification via email that alarm.com was successfully logged into by your app, but no commands are coming through to the panel. Maybe alarm.com changed something on their website causing this.

**Comment by adrian97c** [comment]
Yes, the app no longer working as of this morning. Swhark, I will gladly pay you for an update to this app. Plz help

**Comment by MattAH64** [comment]
@schwark i am willing to donate for your time as well. Thanks in advance

**Comment by ericediger** [comment]
Ditto ^

**Comment by edgedout** [comment]
+1 on this issue and on payment for correction. Loved this app before this morning when automation failed to disarm my alarm and I woke up the house while letting the pets outside. Haha

**Comment by adrian97c** [comment]
He might not be reading this thread... have you all tried messaging him on Smartthings forum?

**Comment by schwark** [comment]
I am seeing these :) Unfortunately I am slammed right now, but my system is broken too, so I will fix this.. May take till the weekend before I can get to it though..

**Comment by MattAH64** [comment]
Thank you very much

**Comment by adrian97c** [comment]
Thx Schwark! If you can nail down the silent option as well... hey everyone, pls don’t forgot to donate for his time. Good people!

**Comment by timgoodrich** [comment]
+1 on funding the time spent. This is key to my automation/security integration.

**Comment by tybritten** [comment]
I started poking around on this today. looks like they've switched to a single web interface for mobile/desktop so the old /pda interface that this uses is gone. 

This one has a ton of client side javascript. yuck.

**Comment by jeffrangel1** [comment]
+1 for donating.

**Comment by yelledbett** [comment]
It looks to me like alarm.com instituted some actual api standards to their framework. (This might be the start of something really good from them if they actually/eventually include oauth tokens).

I see a post for disarm (Curious what that number is for)
`POST /web/api/devices/partitions/93993655-127/disarm`

post for armStay
`POST /web/api/devices/partitions/93993655-127/armStay`

It looks like the cookie & ajaxrequestuniquekey has the auth details that you need to simulate the request. 

`ajaxrequestuniquekey: DOt8WKsNEwrdyuxxxxxxxxxx==`

`
Cookie: BIGipServer~AlarmApplication~Alarm_WEBADC_Alarm_HTTP=<TOKEN>; ASP.NET_SessionId=<SESSION_ID>; CultureInfo=en-US; twoFactorAuthenticationId=<TWO-FACTOR-AUTH>; optimizelyEndUserId=oeu<OEU-ID>; optimizelySegments=%7B%222703860207%22%3A%22gc%22%2C%222705860044%22%3A%22direct%22%2C%222713750013%22%3A%22false%22%2C%222727330005%22%3A%22none%22%7D; optimizelyBuckets=%7B%7D; s_fid=<???? NO IDEA ????>; s_cc=true; s_nr=1520026431282-New; s_sq=%5B%5BB%5D%5D; cookieTest=1; IsFromNewSite=1; loggedInAsSubscriber=1; afg=<?? NO IDEA??>==; _ga=GA1.2.2120984985.1520026434; _gid=GA1.2.1014370914.1520026434; __utma=51243513.2120984985.1520026434.1520026438.1520026438.1; __utmc=51243513; __utmz=51243513.1520026438.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmv=51243513.|1=VisitorType=Customer=1; __utmb=51243513.20.10.1520026438; auth_CustomerDotNet=<CUSTOMER_TOKEN_OF_SOMESORTS>; _gat=1; BIGipServer~AlarmApplication~Alarm_WEBADC_Alarm_HTTPS=!OB8d89wCgIdx+<ANOTHER AUTH TOKEN>=
`

I don't know the current groovy code well enough to try to edit this or I would.

**Comment by schwark** [comment]
Ok - this should be working now. And maybe those that did not have silent work before will have it work now..

**Comment by edgedout** [comment]
Thank you so much!  If you have a way to donate for your time I will.  So glad you were able to get it to work.  Solid work Schwark!

**Comment by dylgojoe** [comment]
Do we need to reinstall it?




On Mar 3, 2018, at 4:55 PM, Schwark Satyavolu <notifications@github.com> wrote:

Ok - this should be working now. And maybe those that did not have silent work before will have it work now..

**Comment by jeffrangel1** [comment]
@dammittman813 I just updated the smartapp and that fixed it. No need to re-install everything.

**Comment by adrian97c** [comment]
I can confirm, silient arming works finally! Nice! 

Bug alert - refreshing switch status from within the switch window/view triggers disarm command :(

**Comment by leftride** [comment]
edit: my fault, everything is working now, needed to uninstall/reinstall

with the updated code Disarm is working for me, but Arm Stay and Arm Away aren't.  Anyone have ideas?

seems like the issue is around here:

debug getCommand got command null with silent true and nodelay of false
error something went wrong: groovyx.net.http.HttpResponseException: Unprocessable Entity
debug postbody:https://www.alarm.com/web/api/devices/partitions/92034855-127/armAway::{"forceBypass":false,"noEntryDelay":false,"silentArming":true,"statePollOnly":false}

**Comment by fjlugo63** [comment]
<img width="816" alt="screen shot 2018-03-09 at 9 55 11 pm" src="https://user-images.githubusercontent.com/37230447/37237690-f0820590-23e4-11e8-9d6d-acf1789eaff4.png">
help!.....getting attached log errors at device handler simulator:

Any suggestions on how to fix?
