### ISSUE TITLE
New Version: Refresh not working

### ISSUE THREAD

**Issue by akalderon** [schwark/smartthings-alarmcom#13]
Thanks so much for fixing the integration and a bunch of us want to send you money for your time and hard work.  

Bug in the latest fix - Refreshing the switch (Arm Away or Arm Stay) causes a disarm event vs. updating true status of the switch.  This worked in the prior version fine and was very useful as I was triggering a refresh based on several events to inquire if the alarm is armed away, stay or disarmed.

Seems like a typo / cut+ paste in the code line below?

> 'STATUS': ['params': ['command':'**disarm**', 'silent': silent?'true':'false',...

I tried to update the command to: status and even to blank - seems like refresh does not update the switches.  Please advise?

Thank you.

**Comment by ae249** [comment]
Thank you for fixing this! I too am having an issue with the refresh button sending the disarm command. I also noticed if there is an alarm dot com login id that has limited access this will not allow user to arm or disarm but they can thru the website. Any idea why it won’t work thru smart app?

On Mar 3, 2018, at 5:43 PM, akalderon <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks so much for fixing the integration and a bunch of us want to send you money for your time and hard work.

Bug in the latest fix - Refreshing the switch (Arm Away or Arm Stay) causes a disarm event vs. updating true status of the switch. This worked in the prior version fine and was very useful as I was triggering a refresh based on several events to inquire if the alarm is armed away, stay or disarmed.

Seems like a typo / cut+ paste in the code line below?

'STATUS': ['params': ['command':'# disarm', 'silent': silent?'true':'false',...

I tried to update the command to: status and even to blank - seems like refresh does not update the switches. Please advise?

Thank you.

**Comment by adrian97c** [comment]
I also found same glitch. I’d still like to tip you Schwark. We appreciate your coding skills & your quick fixes!

**Comment by ralphieq** [comment]
Changing:
`'STATUS': ['params': ['command':'disarm', 'silent': silent?'true':'false', 'nodelay': nodelay?'true':'false'], 'name': 'Status', button: false]`
To: (From original script)
`'STATUS': ['params': [], 'name': 'Status', button: false]`
Worked for me.

**Comment by adrian97c** [comment]
@ralphieq

Which # lines are are you replacing? Are you removing the silient alarming in error?

I think I’ll just wait for Schwark to update it. I’ll prob screw something up.

**Comment by adrian97c** [comment]
@ralphieq I don’t want to lose the silient arming function. I’m so glad it finally works! By making the edit you describe, have you gone back & tested that it still works?

**Comment by leftride** [comment]
the updated code is allowing me to disarm without issue, but arm away and stay aren't working.

**Comment by adrian97c** [comment]
Ok just released Schwark updated code 8 hrs ago & titled the update “Partial fix”.

**Comment by akalderon** [comment]
@ralphieq  - This fix just subdues the 'disarm' active on refresh but does not restore the desired functionality to what refresh is supposed to be doing which is querying alarm.com to the status.

This is particularly of importance for the use case where you arm / disarm at the panel and want ST to poll and update status accordingly.   I have a relay that does that in a hardwired manner (updates ST of arm/disarm status) but knowing if alarm.com is in away or stay mode required a status inquiry which was the way the old script was handling.

I am sure it is a small update for Schwark to figure out the new API and will await his response.

**Comment by adrian97c** [comment]
A few updates have been published during the last hour (thx Schwark!), no longer sends "disarm event", but status still isn't working, hitting refresh will only change active switch from 'on' to 'off'. I'm testing as he updates since I have the day off, I'll be the beta tester today 👍

**Comment by ralphieq** [comment]
@akalderon Yes. I didn't catch the problem with refreshing the system state. Found out this was a problem when there was a desync between my mqtt bridge and the alarm state when arming through the alarm.com android app. Glad you posted as I thought I might have broken something in my config. Trying the latest push to see if everything is working now.

**Comment by ralphieq** [comment]
No dice as @adrian97c and others have posted. System status still not reporting.

**Comment by adrian97c** [comment]
New push 5:40pm, unfortunely status still gets switched from “on” to “off” upon refreshing currently active switch.

**Comment by adrian97c** [comment]
5:40p update: Refresh seems to work! I’m having an issue with my ST goodbye routine (or just tapping Arm outside of routine) NOT triggering all the time, using alarm.com history, I can see it smartapp logs in, but the command doesn’t get triggered. Still spotty.

**Comment by adrian97c** [comment]
5:40p update Refresh worked, although i first reported it didn’t. I updated my previous post to reflect that it did in fact work..(sorry for confusion), but another update was pushed shortly after & I updated to it @ 7:35p (eastern), so I’m reporting on that one now (most recent), still works on refresh 👍

**Comment by schwark** [comment]
It is a little iffy - I see socket timeouts on some calls. I have added some caching of some ids that I don't think change much to reduce the number of network calls - this should speed it up some and also make it more reliable.

**Comment by danielkao8** [comment]
Arm Stay doesn't work for me, shows successful web login but no command.

**Comment by adrian97c** [comment]
I Updated Device handler & App 9:10p (eastern), will continue to test in the morning (heading to bed soon). @danielkao8 update using ST intergration as he pushes updates to make sure you are testing the most up to date.

**Comment by akalderon** [comment]
Looks like it is refreshing but somewhat inconsistently as per @schwark above.  I'll do some more testing tomorrow as well.  Thank you all for all your efforts!

Quick question - is there a way to switch to the ST git integration you just initiated **without** having to delete the current switches and smartapp?  Basically link the repo version with the current instances on the backend?
I have quite a few automation dependencies on the switches that I wouldn't want to recreate again if it can be avoided, yet, I'd like to leverage the git integration moving forward vs. the copy-paste.

Thanks again

**Comment by adrian97c** [comment]
Good morning, it’s 7:30a eastern here, Just updated to newest build that was pushed 7 hrs ago, will test. Thx!

**Comment by adrian97c** [comment]
Tested newest build, failed to trigger Arm away upon leaving home for work this morning ☹️

**Comment by adrian97c** [comment]
Just updated to latest push at 10:15a eastern (Im at work, but still checking the repo lol, don’t tell my Boss), will test..

**Comment by adrian97c** [comment]
Recent build (9:30a eastern) still requires tapping switches few times (sometimes it works perfectly)before command is successfully triggered. I’ll continue to test during next hour to test for accuracy/consistency.

**Comment by akalderon** [comment]
Confirming inconsistent behavior on switch actuation registering with alarm.com on this end as well.  

On the flip side, in this version the switches refresh status within 10 seconds of changes made in the panel without requiring an explicit refresh method to be called for each switch which is awesome :-)

**Comment by akalderon** [comment]
By the way, answering my own question a few items above,  i just published on the community page, a small tutorial on how to move existing code to git-based given that many of us may have several integration dependencies that would be a pain to recreate if we were to completely remove and redo.

I hope it is ok, @schwark and @bumpaneer - it is posted [here](https://www.evernote.com/shard/s3/sh/aa52a3dd-7602-40c4-bea2-3ae7f4838027/d2e470e57ad6bacf).

**Comment by adrian97c** [comment]
Wife was so used to Alarm being disarmed with my ‘Good morning’ ST routine, but it didn’t send command due to the timeout bug, so when she opened the door alarm went off. Yikes that woke me up!

**Comment by ralphieq** [comment]
@adrian97c You're not alone on that one. WIfe has triggered the alarm three times in the past couple of weeks. Had the alarm on a schedule in ST to shut off in the morning. She leaves before me to work so it makes for one crazy alarm clock :).

@schwark Haven't seen any posts recently so not sure if fix is 100% but I wanted to point this thread out in case it wasn't.
https://github.com/home-assistant/home-assistant/issues/12694

**Comment by schwark** [comment]
will not have time to look at it till the weekend - but I would recommend that you add a second scheduled event shortly after the first to try the operation again - it will probably work 100% of the time with two tries.

The issue is not the protocol - I have it working perfectly in python. The issue seems like the http implementation in smartthings and alarm.com new server are causing sockets to time out for some reason.

**Comment by ralphieq** [comment]
@schwark Gotcha. I'll give that a shot. Thanks much!

**Comment by adrian97c** [comment]
Thx for the updates @schwark hopefully this weekend will uncover the mystery with time-outs. Cheers!

**Comment by adrian97c** [comment]
Its still missing commands. I added backup commands as backup, but I tried taking off backup to see if it started working on its own again.. but sadly nope.

**Comment by adrian97c** [comment]
New update pushed, thx @schwark . I will start testing 👍🏽

**Comment by akalderon** [comment]
Thanks @schwark - at first blush seems like it works reliably but i haven't tested heavily yet.  Appreciate the hard work and attention 

AND - at one point you cannot avoid the question anymore.  A bunch of us want to send you money for your efforts - would you share your paypal or other means for doing so?  No strings attached, promise!

**Comment by leftride** [comment]
agreed, after initial testing all 3 buttons are working reliably.  I’ve added them back to my routines so we’ll see how it goes over the next few days!

thanks @schwark

**Comment by ericediger** [comment]
“No strings attached, promise!”

*Until the next time it breaks...

j/k - ready to send some cash!!!

**Comment by akalderon** [comment]
:-)   ain't that the truth

**Comment by adrian97c** [comment]
@ryant80 look in here
