### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by BinaryShrub** [schwark/smartthings-alarmcom#2]
First off I want to say thanks! This is great!

Here are some suggestions to make it perfect for my needs:
1) refresh button state when alarm is armed or disarmed outside of the Smart App
2) if user enables "disarm" then use the off state of the switch to send the disarm command (hinges on 1)
3) When arming, don't switch on until the success callback is received from alarm.com

**Comment by BinaryShrub** [comment]
If pulling for the status is not an option, I'd consider switching from using a "switch" to a "Momentary Button Tile" so it is easier to integrate to routines.

**Comment by schwark** [comment]
The switch already has a momentary capability and I just added an actuator capability since apparently ActionTiles requires that.
