### ISSUE TITLE
Arm Away and Stay Status not updating

### ISSUE THREAD

**Issue by pghattas** [schwark/smartthings-alarmcom#22]
I have the disarm disabled in my setup so the only way to disarm is through the physical security panel or the alarm.com app.  Arm the system both Stay and Away works perfect.  When I use one the method to arm/disarm (ADC app or physical) the status does not change for either Arm status inside ST app.  Is there a polling interval that can be modifed, if there is, what is it set to?

**Comment by schwark** [comment]
There is polling that eventually updates status, but it is not real time. The polling frequency is not modifiable. The reason is that if you hit alarm.com too frequently - they may end up making it harder for this kind of approach to work by blocking.

**Comment by pghattas** [comment]
Thanks schwark.  The integration is awesome and just what I was looking for.  I have the SA and DH connected to your repository using your well laid out instructions.  I made sure I have the latest pull and in the ST app did a "save" to refresh status which works.  However, if everytime I change status that is not through ST the status stays stale (waited several hours).  Going into the Smart App and just click Save again will refresh it, but unfortunately I dont think there is a way to automate that.  Let me know if I am missing soemthing or doing something wrong.  Keep up the great work on this, btw
