### ISSUE TITLE
Unable to link your Google Assistant for Alexa Skill. Please try again later.

### ISSUE THREAD

**Issue by jimosity** [schwark/smartthings-alarmcom#3]
I've followed the process and no matter what I do, when I try to link my google account; it'll ask me for my account, tell me to confirm that I accept the access that it's needing...then it gives me this error message.

"Unable to link your Google Assistant for Alexa Skill. Please try again later."

I have 'tried later' a couple times over the last few days and nothing ever changes.
Any ideas?

**Comment by schwark** [comment]
No idea, I think this may not have anything to do with this device manager
