### ISSUE TITLE
Ability to access other alarm.com features?

### ISSUE THREAD

**Issue by jimosity** [schwark/smartthings-alarmcom#4]
How can this code be tweaked to allow access to the other features that alarm.com systems control?
Lights
Thermostats
Image Sensor

These are all things I have in my alarm.com account that I'd like to be able to access; control via SmartThings and ultimately control via ActionTiles.

**Comment by schwark** [comment]
Unfortunately, that requires a full rebuild using the main alarm.com site (I think - not sure if the full site supports it either) which I don't have the time to do unfortunately.
