### ISSUE TITLE
Still working

### ISSUE THREAD

**Issue by jamnmon66** [schwark/smartthings-alarmcom#40]
Hi.  I'm new to SmartThings and I have an Alarm.com security panel.  I followed the instructions and I can see the Alarm.com in my list of SmartApps on the IDE page and I can see the Alarm.com switch in My Device Handlers.  But, I can't find either in the app.  I've been reading that IDE is going to be depreciate (or possibly already has).  Will this method still work or is there another new way to connect Alarm.com to SmartThings?

**Comment by jamnmon66** [comment]
Thanks ahead of time, by the way.  I can see that a lot of great work has been done on this.

**Comment by adrian97c** [comment]
This app stopped working for 98% of us early 2021, due to 2FA. It magically still works for a few, including Schwark. So highly unlikely that he will put any more effort into this project.

Outlook<https://aka.ms/qtex0l> for iOS

________________________________

**Comment by ralphieq** [comment]
Yes Schwark did put a lot of work in to this over the years and adrian97c, glad to see old names still around :) 

There are alternatives out there. Suggest you check out Home Assistant http://hass.io and the custom component https://github.com/uvjustin/alarmdotcom .Its a little more involved getting started but the cost of entry is pretty low (a raspberry pi) and it integrates with smartthings out of the box if you're not ready to scrap your setup.

**Comment by schwark** [comment]
https://community.smartthings.com/t/st-edge-smartthings-alarm-com-integration/246934
