### ISSUE TITLE
Not triggering command

### ISSUE THREAD

**Issue by ashy516** [schwark/smartthings-alarmcom#41]
@schwark, not sure if you are still actively monitoring this thread or tweaking this recipe. This used to work for me 18 months ago, and when alarm.com enabled 2FA, it stopped. It has been abandoned altogether for the past year. Just today, I contacted alarm.com and had them disable 2FA and create a separate account with less privilege. The account can arm/disarm via the alarm.com website. Re-established it with the Smartthings alarm-com.groovy code. When it's triggered via Smartthings App, I can see successful login activities (alarm.com) from the newly created account, but it's not triggering the arm/disarm of the device. It's as though it's logging in but not completing the trigger command. Not sure what's occurring. Please let me know if you or other community members have any suggestions. Thanks

**Comment by ashy516** [comment]
I should add that I just noticed the disarm command is functional. But not arm stay/away. Thanks

**Comment by schwark** [comment]
I am not actively working on this, but I am in the process of rewriting this whole module to use the new Lua based Edge drivers. So I will try to make this work - from scratch in the new architecture as this whole Groovy thing is gone in a month.

**Comment by adrian97c** [comment]
Great to hear! Looking fwd to having this work again. It’s been a sad few years without it

Outlook<https://aka.ms/qtex0l> for iOS

________________________________

**Comment by ashy516** [comment]
@schwark, thank you for the quick response and this is good news, no pressure! It would be amazing to have this functional again.

**Comment by schwark** [comment]
https://community.smartthings.com/t/st-edge-smartthings-alarm-com-integration/246934
