### ISSUE TITLE
Alarm.com/Smartthings Sensor status

### ISSUE THREAD

**Issue by philkruger57** [schwark/smartthings-alarmcom#5]
Would like to able to pull Alarm.com Sensor status into Smartthings. I Have 2gig door sensors on my garage that do not notify alarm.com but do set status and notify me as to open/close. rather than duplicate with a smart-things sensor I would rather get status. from Alarm.com

**Comment by schwark** [comment]
Unfortunately, the mobile site I use does not support anything else except arm and disarm.
